GET http://localhost:3000/users

###
GET http://localhost:3000/user/300

###
POST http://localhost:3000/createuser
Content-Type: application/json

{
    "id":300,
    "name":"Shyam p",
    "city":"Mumbai"
}

###
PUT http://localhost:3000/updateuser/100
Content-Type: application/json

{
    "id":100,
    "name":"Shyam chopra",
    "city":"Mumbai"
}

###
DELETE http://localhost:3000/removeuser/300

###
POST http://localhost:3000/sum
Content-Type: application/json

{
    "a":10,
    "b":90
}

###
GET http://localhost:3000/read

###
GET http://localhost:3000/user/getusers

###
GET http://localhost:3000/product/getproducts
